### ISSUE TITLE
nnedi3 issue

### ISSUE THREAD

**Issue by TbtBI** [jpsdr/plugins_JPSDR#4]
Hi,
```
colorbars(pixel_type="yv12")
nnedi3()
```
using this script and continuously refreshing it in AvsPmod (F5) or in VirtualDub2 (F2) for like a 1 min., you will see error in AvsPmod or white screen in VirtualDub. It occurs on Avs+ 3.5x but it seems Avs+ 3.6x is fine. The latest version of plugins_JPSDR is used.
Btw using the standalone plugin nnedi3.dll doesn't have that behavior and it's fine.

**Comment by jpsdr** [comment]
I'll investigate later, don't have time right now unfortunately.

**Comment by TbtBI** [comment]
I'm just checking you didn't forget.

**Comment by jpsdr** [comment]
I opened in VDub and hit F2 like crazy during 3 min (my arm still hurting and F2 was still "buffering" at least 1 min after i stoped), and nothing happened...
Can't reproduce, maybe it's an avisynth issue...?

**Comment by TbtBI** [comment]
Yes, it could be an AviSynth+ issue but the error appears with plugins_JPSDR.dll. nnedi3.dll is fine.
I'm using the latest AviSynth+ 3.6x. Tried the latest plugins_JPSDR.dll and it was fine. Switched back to official 3.5.1 and the error appeared - https://images2.imgbox.com/ec/1f/LQmLmLid_o.png
Deleted plugins_JPSDR.dll and used the latest nnedi3.dll, and there was no error (still official 3.5.1).

**Comment by jpsdr** [comment]
Tests i've done for now.
The previous described (not reproduced) was under Windows7 x86 with 2.6.1 avs, but have debuging tools if necessary.
The configuration on my dedicated PC video is under Windows7 x64 with 3.5.2 avs+, not reproduced on VDubx64 (my arm still hurting)... This PC doesn't have (and never will) debuging tool, so even if i put 3.5.1 and reproduced, it will not help.
I'll try to see if i can put 3.5.1 somewhere with debuging tools if i can reproduce. It seems more and more specific to avs+ 3.5.1, which had a lot of issues if i remember properly what i read on doom9 at the time...

**Comment by jpsdr** [comment]
So, i've been able to test with 3.5.1. Didn't have to press F2, issue occurs immediatly. Debug tool showed me issue occured on the call of a new feature introduced in 3.5.
This is clearly an avs+ issue, specific to 3.5.1 with some new features not totaly stable (which may explain why nnedi3 plugin alone worked), i'll not investigate more. Update to 3.5.2 if you don't want tu jump to 3.6.x, or update to 3.6.x, or go down before 3.5, but don't use 3.5.1.

**Comment by TbtBI** [comment]
Ok.
Thanks for you time.
