### ISSUE TITLE
A request if may i

### ISSUE THREAD

**Issue by rpdroky** [jpsdr/plugins_JPSDR#6]
Greetings sir , could you include a antialiasing filter into this awesome plugin pack like SangNom2 ( and if it is posible adding yre magic multithreading into it ) ? it whould help awarpsharpmt dealing with edges

Cheers !

**Comment by jpsdr** [comment]
Sorry, not in my projects.

**Comment by rpdroky** [comment]
> 
> 
> Sorry, not in my projects.

No biggy , thanks anyway ^^
