### ISSUE TITLE
ResizeMT 3.2.5 issue

### ISSUE THREAD

**Issue by ghost** [jpsdr/plugins_JPSDR#7]
Hello JPSDR,

I'm having a crash with 3.2.5 I did not have before.
It is related to specifying a small value of width or height....
I am surprised that I didn't have that in 3.2.4 but now i have it in 3.2.5 although there is a commit that says it addressed it here: https://github.com/jpsdr/plugins_JPSDR/commit/febda056cb80e52065126b723c2425d5d4a0b64f

I use ResizeMt through Staxrip. Did something change in ResizeMT's output ?
Thank you very much !

Edit: it seems that values =<10 makes it crash
Example: `LanczosResizeMT(8, 8, prefetch=4)` => crash

**Comment by jpsdr** [comment]
I tested 3.2.4, and there is also the issue. It seems to occurs before the test added... I'll investigate.

**Comment by ghost** [comment]
I confirm 3.2.4 crashes also (but not the same way, this is why I didn't see it crashing at first). Thanks for looking at it !

**Comment by jpsdr** [comment]
BTW, the fix is the same than core avs, it will just display the same error message than LanczosResize, you'll still not be able to use low values.

**Comment by ghost** [comment]
Well using low values is not my aim.
What happens is that simply by using the UI of staxrip to change manually the values of Height or Width, in v3.2.5 makes it instantly crash. Because manually editing the values is interpreted as inputting very small value (for less than a second, but enough to make crash).
When I use 3.2.4 or core AVS filters, I don't get this instant crash. I need to open a preview of the video or a preview of the code to get the crash.
So even if I get a behaviour similar to core AVS, it's preferable !

And many thanks! (I saw the commits!)
